export interface proveedorInterface {
    id: number,
    nombre: string,
    apellidos: string,  
    nie: string,
    email: string,
    tlf: string,
    tlf_movil: string,
    localidad: string,
    direccion: string,
    cp: string,
    usuario_id?: number,
    borrado: boolean,
    create_time?: Date,
    update_time?:Date,
}