export interface ingresoInterface {
    id: number,
    fecha_concepto: Date,
    concepto: string,
    ingreso?: number,
    gasto?: number,
    proveedores_id: number,
    inmuebles_id: number,
    fecha_factura?: Date,
    numero_factura?:string,
    usuario_id?: number,
    borrado: boolean,
    create_time?: Date,
    update_time?: Date,
}